version: "3.8"
services:
  server:
    container_name: JDR-Back
    build:
      context: ..
      dockerfile: ./JDR-server/Dockerfile
    volumes:
      - ../JDR-server/src:/app/Backend/src:rw
    depends_on:
       db:
          condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - Jdr-net
  db:
    container_name: JDR-db
    image: mysql:8.0.19
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: jdr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - Jdr-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
    - "2001:80"
    environment:
      PMA_HOST : db
      PMA_PORTS : 3306
    networks:
      - Jdr-net
volumes:
  db_data:
networks:
  Jdr-net: