services:
  server:
    extends:
      file: ./docker/server.compose.yaml
      service: server
  db:
    extends:
      file: ./docker/db.compose.yaml
      service: db
  phpmyadmin:
    extends:
      file: ./docker/phpmyadmin.compose.yaml
      service: phpmyadmin

volumes:
  db_data:
  jdr-backend-data:

networks:
  Jdr-net: